language: python
python:
  - "3.5"

notifications:
  email: false

services:
  - docker

install:
  - docker pull araffin/stable-baselines-cpu:v2.7.0

script:
  - ./scripts/run_tests_travis.sh "${TEST_GLOB}"

matrix:
  include:
    # Big test suite. Run in parallel to decrease wall-clock time, and to avoid OOM error from leaks
    - name: "Unit Tests a-h"
      env: TEST_GLOB="[a-h]*"

    - name: "Unit Tests i-l"
      env: TEST_GLOB="[i-l]*"

    - name: "Unit Tests m-sa"
      env: TEST_GLOB="{[m-r]*,sa*}"

    - name: "Unit Tests sb-z"
      env: TEST_GLOB="{s[b-z]*,[t-z]*}"

    - name: "Sphinx Documentation"
      script:
        - 'docker run -it --rm --mount src=$(pwd),target=/root/code/stable-baselines,type=bind araffin/stable-baselines-cpu bash -c "cd /root/code/stable-baselines/ && pip install .[docs] && pushd docs/ && make clean && make html"'
