language: python
python:
  - "3.5"

notifications:
  email: false

services:
  - docker

install:
  - docker pull araffin/stable-baselines-cpu:v2.7.0

script:
  - ./scripts/run_tests_travis.sh "${TEST_GLOB}"

matrix:
  include:
    # Big test suite. Run in parallel to decrease wall-clock time, and to avoid OOM error from leaks
    - name: "Unit Tests a-g"
      env: TEST_GLOB="[a-g]*"

    - name: "Unit Tests h-m"
      env: TEST_GLOB="[h-m]*"

    - name: "Unit Tests m-t"
      env: TEST_GLOB="[m-t]*"

    - name: "Unit Tests t-z"
      env: TEST_GLOB="[t-z]*"

    - name: "Sphinx Documentation"
      script:
        - 'docker run -it --rm --mount src=$(pwd),target=/root/code/stable-baselines,type=bind araffin/stable-baselines-cpu bash -c "cd /root/code/stable-baselines/ && pip install .[docs] && pushd docs/ && make clean && make html"'
